#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-HTML5-Entities
Version  : 0.004
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/HTML-HTML5-Entities-0.004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/HTML-HTML5-Entities-0.004.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhtml-html5-entities-perl/libhtml-html5-entities-perl_0.004-1.debian.tar.xz
Summary  : 'drop-in replacement for HTML::Entities'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-HTML-HTML5-Entities-license
Requires: perl-HTML-HTML5-Entities-man

%description
NAME
HTML::HTML5::Entities - drop-in replacement for HTML::Entities
SYNOPSIS
use HTML::Entities;
my $enc = encode_entities('fish & chips');
print "$enc\n";   # fish &amp; chips
my $dec = decode_entities($enc);
print "$dec\n";   # fish & chips

%package license
Summary: license components for the perl-HTML-HTML5-Entities package.
Group: Default

%description license
license components for the perl-HTML-HTML5-Entities package.


%package man
Summary: man components for the perl-HTML-HTML5-Entities package.
Group: Default

%description man
man components for the perl-HTML-HTML5-Entities package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTML-HTML5-Entities-0.004
mkdir -p %{_topdir}/BUILD/HTML-HTML5-Entities-0.004/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTML-HTML5-Entities-0.004/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTML-HTML5-Entities
cp LICENSE %{buildroot}/usr/share/doc/perl-HTML-HTML5-Entities/LICENSE
cp COPYRIGHT %{buildroot}/usr/share/doc/perl-HTML-HTML5-Entities/COPYRIGHT
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-HTML-HTML5-Entities/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/HTML/HTML5/Entities.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTML-HTML5-Entities/COPYRIGHT
/usr/share/doc/perl-HTML-HTML5-Entities/LICENSE
/usr/share/doc/perl-HTML-HTML5-Entities/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::HTML5::Entities.3
